package:
  name: oasvalidator
  version: 1.0.0

source:
  path: ..

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - cmake
    - ninja

  host:
    - python
    - pip !=22.1.0

  run:
    - python


test:
  requires:
    - pytest
  imports:
    - oasvalidator
  source_files:
    - tests
  commands:
    - python -m pytest

about:
  summary: A FAST Python module to validate the HTTP requests against the OpenAPI specifications of the REST server.
  license_file: LICENSE
